### PR TITLE
Support for subdir paths in gitlab com mode

### PR DESCRIPTION
**Pull request by johanvonboer**
Hi,

We needed support for defining subdir paths when interfacing with gitlab since having our emuDBs directly in the root of the repo will be problematic for us. So I simply added another GET param called 'gitlabPath'.

### CODE REVIEW

**Comment by raphywink** [comment]
reviewing the code now: is it correct that if not set a simple empty string is returned by `getGitlabPathFromSearchObject()` and then the current behaviour isn't effected?

**Comment by johanvonboer** [comment]
That is correct! So it shouldn't affect functionality in any way for people who don't want to use this feature.

**Comment by raphywink** [comment]
Merged and just deployed v1.3.6 :-)

**Comment by johanvonboer** [comment]
Great! :)

**Pull request merged**
