### PR TITLE
Add zero line to ssff track displays

### PR DESCRIPTION
**Pull request by SBRitter**
Draw zero line only if configured.

Zero line is useful for visual inspection of velocity tracks. It's a feature needed at IfL Phonetik Cologne.

Configuration looks roughly like this:
"perspectives": [
      {
        ...,
          "zeroLine": [
            {
              "ssffTrackName": "mytrack",
              "displayLine": true
            }
          ],
          ...
        },
        ...      
     }
]

### CODE REVIEW

**Comment by raphywink** [comment]
Thanks heaps for this! Only question: did you adapt the schema file? Because that new config option will probably cause a invalid EMU-webApp config error (at least it should)...

**Comment by SBRitter** [comment]
I changed the schema to fit the new configuration. I hope the change of the schema is correct. I did not encounter an error before I updated the schema (btw: does "minMaxValLims" appear somewhere in the schema? I'm using this property and it does not cause an error as well).

**Comment by raphywink** [comment]
Just checked and you are correct: `minMaxValLims` and other will simply be accepted because of this: https://github.com/IPS-LMU/EMU-webApp/blob/master/app/schemaFiles/emuwebappConfigSchema.json#L292. Think I might change that to something more strict in the EMU-webApp2 repository though... (this is also something to note: we are currently working on a port of the EMU-web app to angular 6.0 and material design.. which is why I don't want to put too much effort into the EMU-webApp any more)

**Comment by raphywink** [comment]
changed your pull request feature slightly. See here: https://github.com/IPS-LMU/EMU-webApp/commit/239307c0ee51179b3b5a99cb3282e85e02169162

renamed the config option to `horizontalLines` and instead of a `boolean` the presence of the config option is used and you can add multiple horizontalLines not just at 0. I think that will be more flexible in the long run. Will probably release a new version fairly soon... (maybe tomorrow)

**Comment by SBRitter** [comment]
+1

**Comment by raphywink** [comment]
FYI also added it to the file descriptions in the EMU-SDMS manual: https://ips-lmu.github.io/The-EMU-SDMS-Manual/app-chap-fileFormats.html#file-descriptions (not present in the published version yet. Will publish latest on new EMU-webApp release)

**Pull request merged**
