### PR TITLE
Fix for assigning colors to individual signalCanvas - #303

### PR DESCRIPTION
**Pull request by samgregory**
Simple fix for issue #303

### CODE REVIEW

**Comment by MJochim** [comment]
Hi @samgregory and thank you for this fix. I will merge it and make a new release in the week after the next.

**Comment by samgregory** [comment]
Hi @MJochim - that's ok. I'm laid up in bed for a few weeks and decided to put my time to good use. I'll keep working through the issues and see which ones I can fix.

**Comment by MJochim** [comment]
> I'll keep working through the issues and see which ones I can fix.

This part is awesome. Next week I can't contribute, but the week after that I'll merge what you do and can hopefully provide feedback as well. 

> Hi @MJochim - that's ok. I'm laid up in bed for a few weeks and decided to put my time to good use.

This part is less awesome. Hope you get better soon!

**Comment by MJochim** [comment]
I cherry-picked this as 29df4668899cf58a36b69b9fd037fb2ce9f74d22. Thanks again for the contribution!

**Pull request closed without merging**
